/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paint;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Polygon;
import java.awt.Shape;
import java.awt.image.BufferedImage;

/**
 *
 * @author julius
 */
public class LienzoImagenes2D extends Lienzo {

    
    private BufferedImage im;
    private boolean cargada = false;
    /** 
     * Creates new form LienzoImagenes2D
     */
    public LienzoImagenes2D() {
        initComponents();
    }

    public boolean isCargada() {
        return cargada;
    }

    public void setCargada(boolean cargada) {
        this.cargada = cargada;
    }

    
    
    
    public BufferedImage getIm() {
        return im;
    }

    public void setIm(BufferedImage im) {
        this.im = im;
        if(im!=null) {
            setPreferredSize(new Dimension(im.getWidth(),im.getHeight()));
        }
    }
    
    public void paintComponent(Graphics g){
        super.paintComponent(g);
       
        if(im!=null) {
            if(!cargada){
                im.getGraphics().setColor(Color.white);
                im.getGraphics().fillRect(0, 0, im.getWidth(), im.getHeight());
            }
            g.drawImage(im,0,0,this);//Podemos cambiar la posicion inicial
        }
        
    }
    
    public BufferedImage getImage(boolean drawVector){
        if (drawVector) {
            
            VentanaInterna vi = new VentanaInterna();
            Graphics2D g2d = im.createGraphics();
            setAtributos(g2d);
            g2d.setColor(getColor());
            
            for (Shape s : getvShape())
                if(!this.isRelleno())
                    g2d.draw(s);
                else{
                    g2d.fill(s);
                }
        }
        
        
        return im;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
